	-- =================================================  
	-- PACKAGE: FRAMEWORK  
	-- CREATE : 2018.11.6
	-- UPDATE : 
	-- =================================================	
	
	CREATE TABLE AC_UI_PROPERTY (
		PROPERTY_NAME	VARCHAR2(100)   NOT NULL,
		PROPERTY_VALUE	VARCHAR2(1024)  NOT NULL,
		CONSTRAINT AC_UI_PROPERTY_PK PRIMARY KEY (PROPERTY_NAME)
	);
	
	
	CREATE TABLE AC_UI_SEQUENCER(
	SEQUENCER_ID	INTEGER NOT NULL,
	NAME			VARCHAR2(100)   NOT NULL,
	VALUE			INTEGER NOT NULL,
	CONSTRAINT AC_UI_SEQUENCER_PK PRIMARY KEY (SEQUENCER_ID)
	);
	
	
	CREATE UNIQUE INDEX  "AC_UI_SEQUENCER_UIDX1" ON "AC_UI_SEQUENCER" ("NAME"); 
	COMMENT ON COLUMN "AC_UI_SEQUENCER"."SEQUENCER_ID" IS '시퀀서 ID';
	COMMENT ON COLUMN "AC_UI_SEQUENCER"."NAME" IS '시퀀서 이름';
	COMMENT ON COLUMN "AC_UI_SEQUENCER"."VALUE" IS '시퀀서 값';
	COMMENT ON TABLE  "AC_UI_SEQUENCER"  IS '애플리케이션 전역에서 사용되는 시퀀서 정보';
	
	-- =================================================  
	-- PACKAGE: SECURITY  
	-- CREATE : 2018.11.6
	-- UPDATE : 
	-- =================================================	
	-- User 
	
		CREATE TABLE AC_UI_USER (
		  USER_ID                INTEGER NOT NULL,
		  USERNAME               VARCHAR2(100) NOT NULL,
		  PASSWORD_HASH          VARCHAR2(64)  NOT NULL,
		  NAME                   VARCHAR2(100),		  
		  NAME_VISIBLE           NUMBER(1, 0)  DEFAULT 1 ,
		  FIRST_NAME             VARCHAR2(100),		  
		  LAST_NAME              VARCHAR2(100),		
		  EMAIL                  VARCHAR2(100) NOT NULL,
		  EMAIL_VISIBLE          NUMBER(1, 0)  DEFAULT 1,
		  USER_ENABLED           NUMBER(1, 0)  DEFAULT 1, 
		  USER_EXTERNAL			NUMBER(1, 0)  DEFAULT 0, 
		  STATUS                 NUMBER(1, 0)  DEFAULT 0,
		  CREATION_DATE          DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE          DATE DEFAULT  SYSDATE NOT NULL,		    
		  CONSTRAINT AC_UI_USER_PK PRIMARY KEY (USER_ID)
		);		
		
		CREATE UNIQUE INDEX AC_UI_USER_IDX_USERNAME ON AC_UI_USER (USERNAME);
		
		COMMENT ON TABLE  "AC_UI_USER"  IS '사용자 테이블';
		COMMENT ON COLUMN "AC_UI_USER"."USER_ID" IS 'ID'; 
		COMMENT ON COLUMN "AC_UI_USER"."USERNAME" IS '로그인 아이디'; 
        COMMENT ON COLUMN "AC_UI_USER"."NAME" IS '전체 이름';
		COMMENT ON COLUMN "AC_UI_USER"."PASSWORD_HASH" IS '암호화된 패스워드'; 
        COMMENT ON COLUMN "AC_UI_USER"."NAME_VISIBLE" IS '이름 공개 여부';        
		COMMENT ON COLUMN "AC_UI_USER"."FIRST_NAME" IS '이름'; 
        COMMENT ON COLUMN "AC_UI_USER"."LAST_NAME" IS '성';        
		COMMENT ON COLUMN "AC_UI_USER"."EMAIL" IS '메일주소'; 
        COMMENT ON COLUMN "AC_UI_USER"."EMAIL_VISIBLE" IS '메일주소 공개여부';           
		COMMENT ON COLUMN "AC_UI_USER"."USER_ENABLED" IS '계정 사용여부';     
        COMMENT ON COLUMN "AC_UI_USER"."STATUS" IS '계정 상태';	    
        COMMENT ON COLUMN "AC_UI_USER"."CREATION_DATE" IS '생성일자';	    
        COMMENT ON COLUMN "AC_UI_USER"."MODIFIED_DATE" IS '수정일자';	
        
        -- Role
		CREATE TABLE AC_UI_ROLE (
		  ROLE_ID                     INTEGER NOT NULL,
		  NAME                        VARCHAR2(100)   NOT NULL,
		  DESCRIPTION              VARCHAR2(1000)  NOT NULL,
		  CREATION_DATE           DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE           DATE DEFAULT  SYSDATE NOT NULL,	
		  CONSTRAINT AC_UI_ROLE_PK PRIMARY KEY (ROLE_ID)
		);
		
		COMMENT ON TABLE "AC_UI_ROLE"  IS '롤 테이블';
		COMMENT ON COLUMN "AC_UI_ROLE"."ROLE_ID" IS '롤 ID'; 
		COMMENT ON COLUMN "AC_UI_ROLE"."NAME" IS '롤 이름'; 
		COMMENT ON COLUMN "AC_UI_ROLE"."DESCRIPTION" IS '설명'; 	
		COMMENT ON COLUMN "AC_UI_ROLE"."CREATION_DATE" IS '생성일자'; 
		COMMENT ON COLUMN "AC_UI_ROLE"."MODIFIED_DATE" IS '수정일자'; 				
		
		CREATE UNIQUE INDEX AC_UI_ROLE_NAME_IDX ON AC_UI_ROLE (NAME)
		
		-- User Roles  
		CREATE TABLE AC_UI_USER_ROLES (
		  USER_ID                 INTEGER NOT NULL,
		  ROLE_ID                 INTEGER NOT NULL,
		  CONSTRAINT AC_UI_USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID)
		);

		COMMENT ON TABLE "AC_UI_USER_ROLES"  IS '사용자 롤 테이블';
		COMMENT ON COLUMN "AC_UI_USER_ROLES"."USER_ID" IS '그룹 ID'; 
		COMMENT ON COLUMN "AC_UI_USER_ROLES"."ROLE_ID" IS '롤 ID'; 
		
		
		-- User remember me
		CREATE TABLE AC_UI_USER_LOGIN_TOKEN (
			UUID			VARCHAR2(100) NOT NULL,
			USERNAME		VARCHAR2(100) NOT NULL, 
		 	TOKEN 			VARCHAR2(100) NOT NULL, 
		 	LAST_USE_DATE	TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
		);
 
		COMMENT ON TABLE "AC_UI_USER_LOGIN_TOKEN"  IS '인증 정보 저장 테이블';
		COMMENT ON COLUMN "AC_UI_USER_LOGIN_TOKEN"."UUID" IS '시퀀스 값'; 
		COMMENT ON COLUMN "AC_UI_USER_LOGIN_TOKEN"."USERNAME" IS '로그인아이디'; 	
		COMMENT ON COLUMN "AC_UI_USER_LOGIN_TOKEN"."TOKEN" IS '인증 토큰 값'; 
		COMMENT ON COLUMN "AC_UI_USER_LOGIN_TOKEN"."LAST_USE_DATE" IS '마지막 사용일자'; 	
		

	--  COMPANY	
		CREATE TABLE AC_UI_COMPANY (
			  COMPANY_ID                INTEGER NOT NULL,
			  DISPLAY_NAME             	VARCHAR2(255)   NOT NULL,
			  NAME                      VARCHAR2(100)   NOT NULL,
			  DOMAIN_NAME				VARCHAR2(100),
			  DESCRIPTION               VARCHAR2(1000),
			  CREATION_DATE            	DATE DEFAULT  SYSDATE NOT NULL,
			  MODIFIED_DATE            	DATE DEFAULT  SYSDATE NOT NULL,	
			  CONSTRAINT AC_UI_COMPANY_PK 	PRIMARY KEY (COMPANY_ID)
		);
		
		CREATE INDEX AC_UI_COMPANY_DATE_IDX ON AC_UI_COMPANY(CREATION_DATE) ;		
		CREATE INDEX AC_UI_COMPANY_NAME_IDX ON AC_UI_COMPANY(NAME);			
		CREATE INDEX AC_UI_COMPANY_DOMAIN_IDX ON AC_UI_COMPANY(DOMAIN_NAME);			
		
		COMMENT ON TABLE      "AC_UI_COMPANY"  IS '회사 테이블';
		COMMENT ON COLUMN "AC_UI_COMPANY"."COMPANY_ID" IS '회사 ID'; 
		COMMENT ON COLUMN "AC_UI_COMPANY"."NAME" IS '회사 이름'; 
		COMMENT ON COLUMN "AC_UI_COMPANY"."DISPLAY_NAME" IS '출력시 보여줄 회사 이름'; 
		COMMENT ON COLUMN "AC_UI_COMPANY"."DESCRIPTION" IS '설명'; 
		COMMENT ON COLUMN "AC_UI_COMPANY"."DOMAIN_NAME" IS '도메인 이름';
		COMMENT ON COLUMN "AC_UI_COMPANY"."CREATION_DATE" IS '생성일자'; 
		COMMENT ON COLUMN "AC_UI_COMPANY"."MODIFIED_DATE" IS '수정일자'; 		
	
		
	    CREATE TABLE AC_UI_COMPANY_PROPERTY (
		  COMPANY_ID               INTEGER NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT AC_UI_COMPANY_PROPERTY_PK PRIMARY KEY (COMPANY_ID, PROPERTY_NAME)
		);	
		COMMENT ON TABLE      "AC_UI_COMPANY_PROPERTY"  IS '회사 프로퍼티 테이블';
		COMMENT ON COLUMN "AC_UI_COMPANY_PROPERTY"."COMPANY_ID" IS '회사 ID'; 
		COMMENT ON COLUMN "AC_UI_COMPANY_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
		COMMENT ON COLUMN "AC_UI_COMPANY_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 	
		
	-- =================================================  
	-- PACKAGE: UI  
	-- COMPONENT : PAGE 
	-- CREATE : 2018.09.19
	-- UPDATE :
	-- 2018.09.17 - AC_UI_PAGE_BODY_VERSION.SCRIPT 추가 
	-- =================================================	
	CREATE TABLE AC_UI_PAGE(	
		PAGE_ID						INTEGER NOT NULL,
		OBJECT_TYPE					INTEGER NOT NULL,
		OBJECT_ID					INTEGER NOT NULL,
		NAME						VARCHAR2(255) NOT NULL,	
		VERSION_ID					INTEGER DEFAULT 1 NOT NULL,
		USER_ID						INTEGER NOT NULL,
		READ_COUNT          		INTEGER DEFAULT 0  NOT NULL,
		PATTERN						VARCHAR2(255) NULL,	
		CREATION_DATE				DATE DEFAULT  SYSDATE NOT NULL,
		MODIFIED_DATE				DATE DEFAULT  SYSDATE NOT NULL,			
		CONSTRAINT AC_UI_PAGE_PK PRIMARY KEY (PAGE_ID)
	);

	CREATE UNIQUE INDEX AC_UI_PAGE_IDX1 ON REP_PAGE (NAME);
	CREATE INDEX AC_UI_PAGE_IDX2   ON REP_PAGE (OBJECT_TYPE, OBJECT_ID, PAGE_ID);
	CREATE INDEX AC_UI_PAGE_IDX3   ON REP_PAGE (USER_ID);

	CREATE TABLE AC_UI_PAGE_BODY
	(	
		BODY_ID						INTEGER NOT NULL,
		PAGE_ID						INTEGER NOT NULL,
		BODY_TYPE					INTEGER NOT NULL,
		BODY_TEXT					CLOB,
		CONSTRAINT AC_UI_PAGE_BODY_PK PRIMARY KEY (BODY_ID)
    ) ;
	
		
	CREATE TABLE AC_UI_PAGE_BODY_VERSION
	(	
		BODY_ID					INTEGER NOT NULL,
		PAGE_ID						INTEGER NOT NULL,
		VERSION_ID				INTEGER DEFAULT 1 NOT NULL ,
		CONSTRAINT AC_UI_PAGE_BODY_VERSION_PK PRIMARY KEY (BODY_ID, PAGE_ID, VERSION_ID )
   );
   
   CREATE INDEX AC_UI_PAGE_BODY_VERSION_IDX1   ON AC_UI_PAGE_BODY_VERSION (PAGE_ID, VERSION_ID);

		
  CREATE TABLE AC_UI_PAGE_VERSION
   (	
	PAGE_ID					INTEGER NOT NULL,
	VERSION_ID				INTEGER DEFAULT 1 NOT NULL ,
	STATE					VARCHAR2(20), 
	TITLE					VARCHAR2(255), 
	SECURED          		NUMBER(1, 0)  DEFAULT 1,
	TEMPLATE				VARCHAR2(255), 
	SCRIPT					VARCHAR2(255), 
	PATTERN					VARCHAR2(255), 	
	SUMMARY					VARCHAR2(4000), 
	USER_ID					INTEGER	NOT NULL,
	CREATION_DATE			DATE DEFAULT  SYSDATE NOT NULL,
	MODIFIED_DATE			DATE DEFAULT  SYSDATE NOT NULL,	
	CONSTRAINT AC_UI_PAGE_VERSION_PK PRIMARY KEY (PAGE_ID, VERSION_ID)
   ) ;

		
	CREATE INDEX AC_UI_PAGE_VERSION_IDX1   ON AC_UI_PAGE_VERSION (CREATION_DATE);
	CREATE INDEX AC_UI_PAGE_VERSION_IDX2   ON AC_UI_PAGE_VERSION (MODIFIED_DATE);
	CREATE INDEX AC_UI_PAGE_VERSION_IDX3   ON AC_UI_PAGE_VERSION (TITLE);
	CREATE INDEX AC_UI_PAGE_VERSION_IDX4   ON AC_UI_PAGE_VERSION (PAGE_ID, STATE);

			
	CREATE TABLE AC_UI_PAGE_PROPERTY (
		  PAGE_ID				INTEGER NOT NULL,
		  VERSION_ID				INTEGER DEFAULT 1 NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT AC_UI_PAGE_PROPERTY_PK PRIMARY KEY (PAGE_ID, VERSION_ID, PROPERTY_NAME)
	);	

	COMMENT ON TABLE  "AC_UI_PAGE_PROPERTY"  IS 'PAGE 프로퍼티 테이블';
	COMMENT ON COLUMN "AC_UI_PAGE_PROPERTY"."PAGE_ID" IS 'PAGE ID'; 
	COMMENT ON COLUMN "AC_UI_PAGE_PROPERTY"."VERSION_ID" IS 'PAGE VERSION'; 	
	COMMENT ON COLUMN "AC_UI_PAGE_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
	COMMENT ON COLUMN "AC_UI_PAGE_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 	 		
	
	-- =================================================  
	--  VIEWCOUNT	
	-- =================================================	
	CREATE TABLE AC_UI_VIEWCOUNT(	
		ENTITY_TYPE					INTEGER NOT NULL,
		ENTITY_ID					INTEGER NOT NULL,
		VIEWCOUNT					INTEGER NOT NULL,
		CONSTRAINT AC_UI_VIEWCOUNT_PK PRIMARY KEY (ENTITY_TYPE, ENTITY_ID)
   	);		
   		
   	COMMENT ON TABLE "AC_UI_VIEWCOUNT"  IS '뷰 카운트 테이블';
	COMMENT ON COLUMN "AC_UI_VIEWCOUNT"."ENTITY_TYPE" IS '객체 타입'; 
	COMMENT ON COLUMN "AC_UI_VIEWCOUNT"."ENTITY_ID" IS '객체 아이디'; 
	COMMENT ON COLUMN "AC_UI_VIEWCOUNT"."VIEWCOUNT" IS '카운트'; 
	