
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (1,'USER', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (2,'GROUP', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (3,'COMPANY', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (4,'ROLE', 4);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (5,'CATEGORY',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (8,'COMMENT',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (10,'ATTACHMENT',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (11,'IMAGE',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (13,'AVATAR_IMAGE',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (14,'PAGE',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (15,'PAGE_BODY',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (30,'API',1);


Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (1,'ROLE_ADMINISTRATOR','관리자 롤');
Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (2,'ROLE_DEVELOPER','개발자 롤');
Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (3,'ROLE_USER', '일반 사용자 롤');

